import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Menu from "./Menu";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Maza&apos;s blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
